service:
  - docker

env:
  global:
    - secure: "BiYSkkfrmmrQfYV0/WDqCXVjkpPOwnVm5vtYwZWqNv0Jm7nTEPZDglEt8YoVkfDsbaD2VsINWrzbTtklYT42dhKv64L0mjz2Hvd6ZAgAeLHBaZQuJUY4V6f3GiSCkAKmCpG8eiw3DH5w6ios74gywf4fWEciZiK/ux3n/7s6Jnz2eijVMq7Ztioi2NURLym/B+yaWkorOv+EHrKbsFP1CO8Md3DqT4ET1SZM/p6mS1W5diDsaRZQUZi//wfk2Zz2HZXGnGtSpblCuY9dUen3E9p7B6TGJjX1zokR9ksmggh5JUFoHRmJA8+HDrnvmXV/RunwW6VSht04IUsX7X81Px2YCpcCXWN0adYCKFsiSzq52Th7/THNvkiLUnShELHjazv4+kG7r7xPN9BjkM8HHQJZNv/J+M6VTSncJR6f9djW6fahU0Fo1rIYquFSGVPlqShlC3f2sxH9NE+iih0ksUbSlL7D5HabOOfwndpQZsO0XcVk1BqSrSSS+nHKhNNzsrbSYTlVZXXLPcUpj5oNc2S4TmEaczJUBtsqb+3YrT7/hHWmU9WeyB/Mf/8tQJih7cMNrT3os2hSgEU6XFDBSt2jYusDCPJX6pRB0+YtF5FHSyVrI4g17cR34UGEhYqUuySvDsyMyFXZPUKZyr1LI0h1dHjFd0cXDhX0mQQE1w4="
    - secure: "k+Pl3l0mdyh2wnFCAI8mQPT3Wr7uaZXDqcgTtYegusHbJ06GnUgY0JJIQ4dIJSl9r3p9nPJVn77Lx+lIvuC27uA7+rb9MtBA6GeKfDRCD3/97QMePBH5o8zeUcthrNOa9X1aTkzYR51XTVhQxvJ96QjGUHeg8Tf0gt8FuuAaTQXXPf0yo/+9e/WMDmO3K3gtCFGZ4sZYyTOeU+XIpEFWM07ah/jLSjqM5dxzD2bBu4/8p/Teus4CWzC/JJvDBocK2C4qQe1AI+AwBofHKHhVnlaQSntyjTXhELbil7YQQUbdCQEkuU2THEGZhOCWGOxVMlbzpGbL6G0NRxqbXpZ3zXF4BxG2v5vx9viDlZI7Mf5W3kIK8tGxQiJn8NbuyXnc9G/YfR9NQiI7q/A7WlZmVPH6R5WfM6lkwE1oLAAe5CIZvr5RMheRVKCst2sNANnOrl8IBKhEQH0g4CS5j1I25J8sNAq58xiGREBLA9Y9XRnUC9N5DfgvbGxfVGmEUVscwGMf6dLRGi12ICbl0HdPFuhq3CIFXAxhj6zng5POmmIieoEOA2ZqGNuPyvIqiLhHDjEPjNeqVowJUJgAdAq7SbucumvAuStHAktXYIyKCT7xd5dBCF1lfplczDw53ToPZ5uNEzKN5IGAsiLkuQVUnPINkU7Q4LZEdkxwa4jt5/E="
    - secure: "CREVo+UEjVjGWFA76ghRhBP5Hnu2Cl+x9Mo6TkgF4PsZknnM+kDh78+L7qcx65f7tcRkQoaetmX1BDIrHR8bg2wcnEHLKdYWAryB924nYyZWx+pD3d3PNu/U4FsFTzaUHTX3CYOWikWyIN8vu9ozOyEZtI/K8S9sou5QikhlrCxDOEgyuzO2xhuZAMOUOCT+LueAdF3DQnGAF2QDvK/ClGIeL0bgENQ9CxPYWyau4NrX2i3hUzJyy6WnUuc3ZcEg/xF8Zmhh8uiDVRnOXkdOo+TWrLZsZFSMQR3v/VZKqsBC5tvz51tIRKULpz8eSHRiHx+H9Et7CXNZBRZCF218BFvpzFaYTOLTU7M0iwS882t6jYl2mMFuHrntSpDGRtISzFOKAIxbQLnCnc7Azmo9oBoUjNK9TVejS3H1wPZJGr8cd2p2xX+pO4S8DcZ74ih99Gtyj93m2RLUEN7dxS6EyjGGifuKwFSebFYA/5L4IkIyd0aLUh6+bBByN0q9ncioDT13Yb/zT70umCPvkmZA0pYgSi9F9SwIdtBHiaY12HoFrRBmAVYY5cd7HZJEZhQh31JY5acVEIZp7QGloR7ehCQDE2nXcDxO5Swsm7pJUa5hGAI5DGAsvMkN8qydZOqdlK6uxSCxIBnDxTAt24wT0IXN3h9hvCgLJeUMY+gRLU0="
  - STAGE=current RELEASE=trusty
  - STAGE=current RELEASE=trusty RUBY=2.2.0


script:
  - if [ -z "$RUBY" ];
    then ubuntu/build-rubies.sh $STAGE $RUBY $RELEASE
    else ubuntu/build-releases.sh $STAGE $RELEASE
    fi

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - if [ -z "$RUBY" ];
    then ubuntu/push-rubies.sh $STAGE $RUBY $RELEASE;
    else ubuntu/push-releases.sh $STAGE $RELEASE;
    fi
